CREATE TABLE POSTS
(
    ID NUMBER PRIMARY KEY,
    CATEGORY VARCHAR2(100),
    TITLE VARCHAR2(255),
    CONTENT CLOB,
    AUTHOR VARCHAR2(100),
    CREATED_DATE DATE DEFAULT SYSDATE,
    UPDATED_DATE DATE,
    VIEWS NUMBER DEFAULT 0
);

CREATE OR REPLACE TRIGGER POSTS_BI
    BEFORE INSERT ON POSTS
    FOR EACH ROW
BEGIN
    SELECT POST_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
